"project_id": "423866"
"api_token": "c0af1228a152e002ec3db76d6d623762b03aab222058a538deae776f9a3202f23148f1c3fc7228d8"
"base_path": "."
"base_url": "https://api.crowdin.com" # https://{organization-name}.crowdin.com

"preserve_hierarchy": true

"files": [
  {
    "source" : "src/silid-server/public/languages/eng.json",
    "translation" : "%original_path%/%three_letters_code%.json"
  }
]
