version: '3'
services:
  node:
    build: .
    restart: unless-stopped 
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=reg.example.com
      - LETSENCRYPT_HOST=reg.example.com
      - LETSENCRYPT_EMAIL=daniel@example.com
    volumes:
      - .:/home/node
      - /home/node/node_modules
networks:
  default:
    external:
      name: nginx-proxy

