#### docker-compose.yml
# deploy silid-server unit test
#
version: "3"
services:
  # application under test
  test-app:
    build: .
    depends_on:
      - test-app-db
    command: npm test
    volumes:
      - .:/app/
      - test-app-node_modules:/app/node_modules
    environment:
      POSTGRES_HOST: test-app-db
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: pass

  # ephemeral testing database
  test-app-db:
    image: postgres:10.12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: pass

volumes:
  test-app-node_modules:
