# 2019-10-24 Swiped from here: https://codewithhugo.com/node-postgres-express-docker-compose/
# docker-compose.yml
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-ci
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - ./silid-server:/app/
      - /app/node_modules
      - /app/build
    environment:
      - LETSENCRYPT_EMAIL=daniel@capitolhill.ca
      - LETSENCRYPT_HOST=id.whatdandoes.info
      - VIRTUAL_HOST=id.whatdandoes.info
      #
      - AUTH0_AUDIENCE=https://id.languagetechnology.org/
      - AUTH0_CLIENT_ID=tjrl8aOQEx9AtQhFffuWmvP6bcHM7nXB
      - AUTH0_CLIENT_SECRET=some_secret
      - AUTH0_DOMAIN=silid.auth0.com
      - CALLBACK_URL=http://localhost:3001/callback
      - NOREPLY_EMAIL=noreply@example.com
      - NOREPLY_PASSWORD=secret
      - ROOT_AGENT=root@example.com
      - SERVER_DOMAIN=http://localhost:3001
      #
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=silid_staging
      - POSTGRES_HOST=postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: silid_staging
    volumes:
      - silid_postgres_data:/var/lib/postgresql/data
volumes:
  silid_postgres_data:

